### ISSUE TITLE
Accessing to traverser's view identifier in context Resolver.

### ISSUE THREAD

**Issue by fbessou** [makinacorpus/angular-traversal#1]
Hi @ebrehault. I am currently working on a project using angular-traversal. In my context resolver, I need to know the actual traverser's view identifier in order to resolve the context. That would involve passing the view identifier to the resolve function.

Use case:
The context is obtained by fetching `/path/schema?role=update` if the view identifier is `@@edit` and `/path/schema?role=view` if the view identifier is `@@view`.

Do you think it breaks the Traversal pattern ?

**Comment by ebrehault** [comment]
It sounds legit.
I will make that change.

**Comment by fbessou** [comment]
Thanks !

**Comment by ebrehault** [comment]
It was easy, apparently Typescript lets us declare `abstract resolve(path: string, view: string): Observable<any>;` and implement it as `resolve(path: string): Observable<any>;`

**Comment by fbessou** [comment]
Same behavior with interfaces... Nice feature.
