### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by tdesvenain** [makinacorpus/angular-traversal#15]
Hi @ebrehault Could we have a 1.0.5 release ?
Thanks

**Comment by ebrehault** [comment]
Done :)

**Comment by tdesvenain** [comment]
thanks !

Le mar. 20 mars 2018 21:15, Eric BREHAULT <notifications@github.com> a
écrit :

**Comment by sunew** [comment]
@ebrehault Hi:) Where was this release made from? I cannot see the "# 1.0.5 (2018-03-20)" changelog entry from the npm distribution in this repo - did we move repo - or missing commit?

**Comment by ebrehault** [comment]
Oh, well I just forgot to push :)
Fixed.
